import type { Movie } from "./types";

/** Shown when TMDB_API_KEY is missing so the UI is still reviewable. */
export const DEMO_MOVIES: Movie[] = [
  {
    id: 278,
    title: "The Shawshank Redemption",
    overview:
      "Imprisoned men bond over years, finding solace and eventual redemption through acts of common decency.",
    posterPath: "/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdropPath: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    releaseDate: "1994-09-23",
    year: 1994,
    tmdbScore: 8.7,
    voteCount: 28000,
    imdbId: "tt0111161",
    imdbScore: 9.3,
    genreIds: [18, 80],
    certification: "R",
  },
  {
    id: 238,
    title: "The Godfather",
    overview:
      "The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.",
    posterPath: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    backdropPath: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    releaseDate: "1972-03-14",
    year: 1972,
    tmdbScore: 8.7,
    voteCount: 21000,
    imdbId: "tt0068646",
    imdbScore: 9.2,
    genreIds: [18, 80],
    certification: "R",
  },
  {
    id: 155,
    title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime with the help of Lt. Gordon and District Attorney Harvey Dent.",
    posterPath: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdropPath: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    releaseDate: "2008-07-16",
    year: 2008,
    tmdbScore: 8.5,
    voteCount: 34000,
    imdbId: "tt0468569",
    imdbScore: 9.0,
    genreIds: [18, 28, 80, 53],
    certification: "PG-13",
  },
  {
    id: 424,
    title: "Schindler's List",
    overview:
      "In German-occupied Poland, Oskar Schindler becomes concerned for his Jewish workforce after witnessing their persecution.",
    posterPath: "/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
    backdropPath: "/loRmRzQXZeqG78zJajqm1ndeQ9s.jpg",
    releaseDate: "1993-12-15",
    year: 1993,
    tmdbScore: 8.6,
    voteCount: 16000,
    imdbId: "tt0108052",
    imdbScore: 9.0,
    genreIds: [18, 36, 10752],
    certification: "R",
  },
  {
    id: 13,
    title: "Forrest Gump",
    overview:
      "The presidencies of Kennedy and Johnson, Vietnam, Watergate, and other history unfold through the perspective of an Alabama man.",
    posterPath: "/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg",
    backdropPath: "/qdIMWb6df9e8SuZilC9duOjwuos.jpg",
    releaseDate: "1994-06-23",
    year: 1994,
    tmdbScore: 8.5,
    voteCount: 28000,
    imdbId: "tt0109830",
    imdbScore: 8.8,
    genreIds: [35, 18, 10749],
    certification: "PG-13",
  },
  {
    id: 680,
    title: "Pulp Fiction",
    overview:
      "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    posterPath: "/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdropPath: "/suaEOtk1N1sgg2MTM7oBr2XObnn.jpg",
    releaseDate: "1994-09-10",
    year: 1994,
    tmdbScore: 8.5,
    voteCount: 29000,
    imdbId: "tt0110912",
    imdbScore: 8.9,
    genreIds: [53, 80],
    certification: "R",
  },
  {
    id: 122,
    title: "The Lord of the Rings: The Return of the King",
    overview:
      "Aragorn is revealed as the heir to the ancient kings as the Battle of Pelennor Fields begins.",
    posterPath: "/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
    backdropPath: "/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg",
    releaseDate: "2003-12-01",
    year: 2003,
    tmdbScore: 8.5,
    voteCount: 25000,
    imdbId: "tt0167260",
    imdbScore: 9.0,
    genreIds: [12, 14, 28],
    certification: "PG-13",
  },
  {
    id: 550,
    title: "Fight Club",
    overview:
      "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    posterPath: "/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
    backdropPath: "/fCayJrkfRaCRCThVTF9H7LTdgtY.jpg",
    releaseDate: "1999-10-15",
    year: 1999,
    tmdbScore: 8.4,
    voteCount: 30000,
    imdbId: "tt0137523",
    imdbScore: 8.8,
    genreIds: [18],
    certification: "R",
  },
];
